package com.davidsantiagoiriarte.domain.di

const val NAMED_INJECTOR_API_GIF_REPOSITORY = "NAMED_INJECTOR_API_GIF_REPOSITORY"
const val NAMED_INJECTOR_FAVORITE_GIF_REPOSITORY = "NAMED_INJECTOR_FAVORITE_GIF_REPOSITORY"
